# Generated by Django 4.2.30 on 2026-10-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentrend', '0003_alter_contactmessage_id_alter_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_path', models.CharField(help_text='e.g., images/c1.jpeg inside static folder', max_length=255)),
                ('alt_text', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
