# Generated by Django 4.2.30 on 2026-10-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentrend', '0004_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_path',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
